import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Kopi Artuphay - Cafe Management & QR Order System",
  description: "Sistem pemesanan kafe modern berbasis QR Code meja, layar POS kasir real-time, dan laporan penjualan otomatis.",
  openGraph: {
    title: "Kopi Artuphay - Cafe Management & QR Order System",
    description: "Sistem pemesanan kafe modern berbasis QR Code meja, layar POS kasir real-time, dan laporan penjualan otomatis.",
    url: "https://cafe-app-dusky-omega.vercel.app",
    siteName: "Kopi Artuphay Cafe",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body>{children}</body>
    </html>
  );
}
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
